set -g status-right 'CST #(TZ="Asia/Shanghai" date +"%%H:%%M:%%S")'
set -g mouse on
set -g status-interval 1
set -g default-command "${SHELL}"
set -g default-terminal "screen-256color"
set-option -g history-limit 1000000
set-window-option -g allow-rename off
set-window-option -g automatic-rename off
set-option -g renumber-windows on
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"
